
export const  GET_CART_REQUEST="GET_CART_REQUEST"
export const GET_CART_SUCESS= "GET_CART_SUCESS"
export const GET_CART_FAILURE= "GET_CART_FAILURE"

export const  POST_CART_REQUEST="POST_CART_REQUEST"
export const POST_CART_SUCESS= "POST_CART_SUCESS"
export const POST_CART_FAILURE= "POST_CART_FAILURE"

export const  DELETE_CART_REQUEST="DELETE_CART_REQUEST"
export const DELETE_CART_SUCESS= "DELETE_CART_SUCESS"
export const DELETE_CART_FAILURE= "DELETE_CART_FAILURE"

export const  UPDATE_CART_REQUEST="UPDATE_CART_REQUEST"
export const UPDATE_CART_SUCESS= "UPDATE_CART_SUCESS"
export const UPDATE_CART_FAILURE= "UPDATE_CART_FAILURE"


